### ISSUE TITLE
Crashing on 1.19.3 when opening a chest near nether portals

### ISSUE THREAD

**Issue by arvidlindeby** [wutdahack/ActuallyUnbreakingFabric#14]
Game crashes when opening a chest found nearby randomly spawned damaged nether portals. Using fabric-loader 0.14.2.

**Comment by wutdahack** [comment]
i can't reproduce this crash when using fabric loader 0.14.12, maybe you should update fabric loader?

**Comment by wutdahack** [comment]
i'm unable to reproduce this crash when using fabric loader 0.14.12, maybe try updating fabric loader?

**Comment by arvidlindeby** [comment]
No, sorry, the bug still persists after updating to 0.14.13. I'm attaching the crash report details.

[crash-2023-01-18_21.48.27-server.txt](https://github.com/wutdahack/ActuallyUnbreakingFabric/files/10451058/crash-2023-01-18_21.48.27-server.txt)

**Comment by wutdahack** [comment]
thanks, can you please test if this works? i still cannot reproduce the crash.

[actuallyunbreaking-1.19.3-0.1.1.zip](https://github.com/wutdahack/ActuallyUnbreakingFabric/files/10456146/actuallyunbreaking-1.19.3-0.1.1.zip)

**Comment by arvidlindeby** [comment]
Yeah, that fixed it, thanks!
