### ISSUE TITLE
Modrinth versions labeled incorrectly

### ISSUE THREAD

**Issue by RandomGgames** [wutdahack/ActuallyUnbreakingFabric#15]
Context: I was browsing through Modrinth, added this mod's link to my mod downloader (I am making a mod pack for myself) not looking at anything else. I notice it fails to download, so I look more into it.

It seems like, at least for 1.19-0.1.0, it is reported as only compatible with 1.19. On CurseForge however, 1.19-0.1.0 lists 1.19-1.19.2 as compatible versions. 
Modrinth:
![image](https://user-images.githubusercontent.com/17207260/225842930-98850d8c-3f07-42a3-bbbb-c6c8c4716cd3.png)
CurseForge:
![image](https://user-images.githubusercontent.com/17207260/225843051-891427eb-e4d5-4e1a-9145-31ec5d899e4e.png)

**Comment by wutdahack** [comment]
sorry about that! i have fixed it now.
