### ISSUE TITLE
add an option to make an item unbreakable only at a specific level of unbreaking

### ISSUE THREAD

**Issue by Asvka02** [wutdahack/ActuallyUnbreakingFabric#19]
For fabric 1.20.1, setting it to only giving unbreakable for a specific level of unbreaking doesn't work properly. It always gives the unbreakable tag for items with unbreaking at the desired level but also for the higher levels. So if I set it to only be unbreakable at level 2, level 2 and 3 would be unbreakable.

**Comment by wutdahack** [comment]
yes that's the intended effect of that setting

**Comment by Asvka02** [comment]
it literally says at that specific level though, not at that specific level or above

**Comment by wutdahack** [comment]
okay i'll make the description for that option more clear then

**Comment by Asvka02** [comment]
If it would be possible it would be great if you could add an option for it to only work on one specific level of unbreaking. If not that is fine but there are literally no other good/working mods for unbreakable tools for fabric out there that also still allow for the normal unbreaking to exist.

**Comment by wutdahack** [comment]
would this new option override both the "max level only" and "unbreakable at level" options?

**Comment by Asvka02** [comment]
Yes. Like you would set it to "unbreakable at unbreaking level 2" and then only items enchanted with unbreaking level 2 would become unbreakable and unbreaking level 1 and 3 would still act normally.

**Comment by wutdahack** [comment]
okay thanks

**Comment by Asvka02** [comment]
Did you update the download for the mod on modrinth or curseforge? Also thank you so so much for actually adding what I suggested. <3

**Comment by wutdahack** [comment]
yeah i've uploaded it to curseforge (although the files haven't been approved yet) and i'm currently uploading it to modrinth and no problem at all :D

**Comment by Asvka02** [comment]
ty <3 <3
