### ISSUE TITLE
Items loose Unbrakable status when combined on anvil

### ISSUE THREAD

**Issue by bentterp** [wutdahack/ActuallyUnbreakingFabric#23]
Hi!
I don't know if it's intentional or not, but when I use an item and the status has changed from ie "Unbreakable III" to "Unbreakable" as noted below the item and I then combine it with another enchanted item using the anvil, then the resulting item has the enchantments as expected but not the Unbreakable status anymore.

Using 1.20.6 now but I noticed the behaviour previously also

**Comment by wutdahack** [comment]
unfortunately this happens even on vanilla minecraft so this issue doesn't have anything to do with my mod. maybe there's another mod that can extract the enchantments from the item and put it on a book so that you can enchant the unbreakable item? i'm sorry but i can't fix this! D:
