### ISSUE TITLE
1.18?

### ISSUE THREAD

**Issue by bentterp** [wutdahack/ActuallyUnbreakingFabric#5]
-hi
Could I ask you for a 1.18 rebuild?

I tried to update the parameters myself but it fails on launch with a `java.lang.ClassNotFoundException: net/minecraft/enchantment/UnbreakingEnchantment` error message.

**Comment by wutdahack** [comment]
it will happen sometime soon, i have no idea when though.

**Comment by wutdahack** [comment]
i've updated it to 1.18! :)

**Comment by bentterp** [comment]
Great, thanks a lot!
As soon as my ISP gets the fiber back up, I will try it out. Will also be good to compare the code with my primitive attempt. Who knows, maybe I'll learn something

**Comment by wutdahack** [comment]
no problem! to be honest, nothing really changed in code except from gradle changes (something like minecraft using java 17).
