### ISSUE TITLE
[Suggestion] Unbreakable (using the unbreakable tag)

### ISSUE THREAD

**Issue by Desempregago** [wutdahack/ActuallyUnbreakingFabric#9]
Let's say you have a tool with Unbreaking 2 and the option to only make tools unbreakable with the max level enabled

As soon as you evolve into Unbreaking 3, the mod REMOVES the enchantment, apply the Unbreakable NBT Tag (vanilla, has a nice tooltip) and make the tool unable to receive Mending and Unbreaking (since it is already unbreakable)

**Comment by Desempregago** [comment]
or make it so if you right click a tool with max level Unbreaking with a Nether Star in your offhand, it consumes the star and makes the tool Unbreakable

**Comment by wutdahack** [comment]
sorry, i've added most of the suggestion but i wasn't able to do it when using a nether star or as soon as you get the max level unbreaking so i decided to make the tool apply the unbreakable tag when the durability is reduced.
